env:
  browser: true
extends: 'airbnb-base/legacy'
rules:
  global-require: 'off'
  max-len: 'off'
  newline-after-var:
    - error
    - always
  no-console:
  - warn
  - allow:
    - debug
    - warn
    - error
  no-multiple-empty-lines:
    - error
    - max: 1
  no-param-reassign: 'off'
